name: Spout
version: ${build.number}
description: SpoutPlugin is a plugin for Bukkit-based servers and a Minecraft client mod system that exposes new API for other plugins to utilize.
author: SpoutDev
website: http://www.spout.org

main: org.getspout.spout.Spout
load: startup
mcversion: ${minecraft.version}

commands:
    spout:
        aliases: [spoutcommand, spoutcmd, spcmd]
        description: Spout commands
        usage: |
            Usage: /<command> version [player]
            Usage: /<command> verify [motd]
