name: Spout
version: ${buildNumber}
description: SpoutPlugin is a plugin for Bukkit-based servers and a Minecraft client mod system that exposes new API for other plugins to utilize.
author: SpoutDev
website: http://www.spout.org

main: org.getspout.spout.Spout
load: startup
mcversion: ${minecraftVersion}

commands:
    spout:
        aliases: [spoutcommand, spoutcmd, spcmd]
        description: Various Spout commands.
        usage: |
            Usage: /<command> version [player]
            Usage: /<command> verify [motd]

permissions:
    spout.plugin.forcespoutcraft:
        description: Forces players to join with Spoutcraft even if the server doesn't force Spoutcraft in the config.
        default: false
    spout.plugin.ignorespoutcraft:
        description: Allows players without Spoutcraft to join even if the server forces Spoutcraft in the config.
        default: false
