name: Spout
version: ${build.number}
description: Spout is a framework to bridge the ever-widening chasm between singleplayer mods, and multiplayer Bukkit plugins.
authors: [Afforess, alta189, Wulfspider, Raphfrk, narrowtux, Top_Cat, Olloth, Rycochet]
website: http://www.getspout.org

main: org.getspout.spout.Spout
load: startup

commands:
  spout:
    aliases: [spoutcommand, spoutcmd, spcmd]
    description: Spout commands
    usage: |
      Usage: /<command> version [player]
      Usage: /<command> verify [motd]
