name: Spout
version: ${build.number}
description: Spout is a plugin for Bukkit-based servers and a Minecraft client mod system that exposes new API for other plugins to utilize, in an attempt to bring the Minecraft multiplayer experience to parity with the single-player modding experience.
authors: [Afforess, alta189, Wulfspider, Raphfrk, narrowtux, Top_Cat, Olloth, Rycochet]
website: http://www.getspout.org

main: org.getspout.spout.Spout
load: startup

commands:
  spout:
    aliases: [spoutcommand, spoutcmd, spcmd]
    description: Spout commands
    usage: |
      Usage: /<command> version [player]
      Usage: /<command> verify [motd]
